/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "MyStm32f407xx.h"
#include <stdint.h>
#include "stm324xx.h"
#include "gpio.h"
#include "rcc.h"
/********************************************************************************
 *********************** Header files ********************************************
 *******************************************************************************/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* RCC (Reset and clock Control) Registers */
#define RCC_BASE_ADDR		0x40023800
#define RCC_AHB1ENR_OFFSET	0x30
#define RCC_AHB1ENR			*(volatile unsigned int *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)
#define BTN_PRESSED ENABLE
/* GPIO Registers */
#define GPIOD_BASE_ADDR		0x40020C00
#define GPIOD_MODER_OFFSET	0x00
#define GPIOD_MODER			*(volatile unsigned int *)(GPIOD_BASE_ADDR + GPIOD_MODER_OFFSET)
#define GPIOD_ODR_OFFSET	0x14
#define GPIOD_ODR			*(volatile unsigned int *)(GPIOD_BASE_ADDR + GPIOD_ODR_OFFSET)



void delay(void);
void igniton_on(void);
void igniton_off(void);
void Clockwise(void);
void wiper_off(void);


#define ADC_BASE_ADDR               0X40012000UL
#define ADC_CR1_REG_OFFSET          0X04UL
#define ADC_CR1_REG_ADDR             (ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR                 0X4002300UL
#define RCC_APB2_ENR_OFFSET           0X44UL
#define RCC_APB2_ENR_ADDR             (RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET)

int main(void)

{
   uint32_t *pRccApb2Enr = (uint32_t*) RCC_APB2_ENR_ADDR;

   uint32_t *pAdcCr1Reg = (uint32_t*) ADC_CR1_REG_ADDR;

   *pRccApb2Enr |= (1<<8);

   *pAdcCr1Reg |=(1<<8);

    long delay = 0xFFFFFFF;

static void on_red_led(void)
{
	volatile long i;
	GPIOD_ODR = GPIOD_ODR | 0x00001000;

}
static void off_red_led(void)
{
	volatile long i;
	GPIOD_ODR = GPIOD_ODR & ~(0x00001000);
}
   static void init_config(void)
{
	config_rcc(GPIOD);
	config_gpiox(GPIOD, PIN_12, GPIO_OUTPUT_PP, GPIO_SPEED_VERY_HIGH); 	//Green LED

	config_rcc(GPIOD);
	config_gpiox(GPIOD, PIN_14, GPIO_OUTPUT_PP, GPIO_SPEED_VERY_HIGH);	//Red LED

	config_rcc(GPIOD);
	config_gpiox(GPIOD, PIN_13, GPIO_OUTPUT_PP, GPIO_SPEED_VERY_HIGH); 	//Orange LED

	config_rcc(GPIOD);
	config_gpiox(GPIOD, PIN_15, GPIO_OUTPUT_PP, GPIO_SPEED_VERY_HIGH); 	//Blue LED

	config_rcc(GPIOA);
	config_gpiox(GPIOA, PIN_0, GPIO_INPUT, GPIO_SPEED_VERY_HIGH);		//Push Button

	config_gpio_irq_priority(IRQ_NO_EXTI0, NVIC_IRQ_PR_LVL_0);			//Interrupt Handler
	config_gpio_interrupt(IRQ_NO_EXTI0, ENABLE);
}
   static void LED_1_ON()
{
	/* Setting PD15 (Pin 15 of PORTD) as General Purpose Output */
	GPIOD_MODER = GPIOD_MODER | 0x01000000000;

	GPIOD_ODR = GPIOD_ODR | 0x00001000;
}

static void LED_1_OFF()
{
	/* Setting PD15 (Pin 15 of PORTD) as General Purpose Output */
	GPIOD_MODER = GPIOD_MODER | 0x01000000000;

	GPIOD_ODR = GPIOD_ODR & ~0x00001000;
   while (1)
	{
		key = gpiox_read_pin(GPIOA, PIN_0); 			

		if(key == 1)
		{
				A = 0;
			long int j;
			for(long int j=0;j<=5000000;j++)
			{
				A++;
			}
}
